version: '3.8'
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=subhanshugupta0@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"

  frontend:
    build: ./frontend
    ports:
      - "80:3000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=atlys123
      - DB_NAME=atlys
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: atlys123
      MYSQL_DATABASE: atlys