name: BE cicd

on:
  push:
    branches:
      - main

jobs:
  setup_env:
    name: 1. Setting up environment
    runs-on: ubuntu-latest
    steps:    
      - name: env setup
        run: |
          sudo apt-get update && sudo apt-get install -y git make bash

  scan_git_secrets:
    name: 2. Scanning Git Secrets
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install git secrets
        run: |
          echo "Installing Git Secrets"
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
      - name: Scan Git Secrets
        run: |
          echo "Scanning Git Secrets"
          source ./backend/ops/ci/git-secrets.sh

  build_and_push_docker:
    name: 3. Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: scan_git_secrets
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
      - name: 5. Set environment variables
        run: echo "APP_TAG_PREFIX=${{ secrets.APP_TAG_PREFIX }}" >> $GITHUB_ENV    
      - name: Build and Push Docker Image
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          APP_TAG_PREFIX: ${{ secrets.APP_TAG_PREFIX }}
        run: |
          bash ./backend/ops/ci/push-docker-image-dockerhub.sh ./server

  create_tag:
    name: 4. Create Tag for Commit
    runs-on: ubuntu-latest
    needs: build_and_push_docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create Git Tag
        run: |
          bash ./backend/ops/ci/create-tag.sh

  deploy_to_server:
    name: 5. Deploy to Server
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy to Server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/subhanshugupta0/atlys-task/backend
            docker-compose pull
            docker-compose up -d
          EOF
