name: GCP webapp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker Images
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy to GCP
      run: |
        ssh your-gcp-vm 'cd /path-to-project && docker-compose pull && docker-compose up -d'