name: FE cicd

on:
  workflow_run:
    workflows: ["Check Changes"]
    types:
      - completed

jobs:
  checkout:
    name: Code Checkout
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.outputs.frontend_changed || 'false') == 'true' }}
    steps:
    - name: Debug Outputs
      run: |
        echo "Frontend Changed: ${{ github.event.workflow_run.outputs.frontend_changed }}"
        echo "Backend Changed: ${{ github.event.workflow_run.outputs.backend_changed }}"
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

  setup_env:
    name: Setting up environment
    runs-on: ubuntu-latest
    needs: checkout
    steps:    
      - name: env setup
        run: |
          sudo apt-get update && sudo apt-get install -y git make bash

  scan_git_secrets:
    name: Scanning Git Secrets
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install git secrets
        run: |
          echo "Installing Git Secrets"
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
      - name: Scan Git Secrets
        run: |
          echo "Scanning Git Secrets"
          source ./frontend/ops/ci/git-secrets.sh

  build_and_push_docker:
    name: Build and Push frontend Docker Image
    runs-on: ubuntu-latest
    needs: scan_git_secrets
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set DockerHub Credentials as Environment Variables
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin
      - name: Set APP_TAG_PREFIX
        run: echo "APP_TAG_PREFIX=${{ secrets.APP_TAG_PREFIX }}" >> $GITHUB_ENV    
      - name: Build and Push Docker Image
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          APP_TAG_PREFIX: ${{ secrets.APP_TAG_PREFIX }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          export DOCKER_HUB_USER=${{ secrets.DOCKER_HUB_USER }}
          export DOCKER_HUB_PASSWORD=${{ secrets.DOCKER_HUB_PASSWORD }}
          bash ./frontend/ops/ci/push-docker-image-dockerhub.sh ./frontend
